In [37]:
# import necessary libraries

import pandas as pd
import numpy as np
from pathlib import Path
import os
import sys
import pylab as pl
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn import metrics
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [2]:
# Read NFL offensive, yearly, team stats into a pandas Dataframe
# Append a column titled "Year" to each Dataframe



off2022 = pd.read_excel('Data/Offense_2022.csv.xlsx')
off2022['Year'] = '2022'


off2021 = pd.read_excel('Data/Offense_2021.csv.xlsx')
off2021['Year'] = '2021'

off2020 = pd.read_excel('Data/Offense_2020.csv.xlsx')
off2020['Year'] = '2020'

off2019 = pd.read_excel('Data/Offense_2019.csv.xlsx')
off2019['Year'] = '2019'

off2018 = pd.read_excel('Data/Offense_2018.csv.xlsx')
off2018['Year'] = '2018'

off2017 = pd.read_excel('Data/Offense_2017.csv.xlsx')
off2017['Year'] = '2017'

off2016 = pd.read_excel('Data/Offense_2016.csv.xlsx')
off2016['Year'] = '2016'

off2015 = pd.read_excel('Data/Offense_2015.csv.xlsx')
off2015['Year'] = '2015'

off2014 = pd.read_excel('Data/Offense_2014.csv.xlsx')
off2014['Year'] = '2014'

In [3]:
# Remove row 32 to 34 
off2022 = off2022.drop([32,33,34])
off2021 = off2021.drop([32,33,34])
off2020 = off2020.drop([32,33,34])
off2019 = off2019.drop([32,33,34])
off2018 = off2018.drop([32,33,34])
off2017 = off2017.drop([32,33,34])
off2016 = off2016.drop([32,33,34])
off2015 = off2015.drop([32,33,34])
off2014 = off2014.drop([32,33,34])

In [4]:
# Merge data together
off_merge = [off2022, off2021, off2020, off2019, off2018, off2017, off2016, off2015, off2014]
off_total = pd.concat(off_merge)
off_total.rename(columns={
    'Rank': 'O Rank'
}, inplace=True)

In [5]:
off_total['Year'] = off_total['Year'].astype('int')

In [6]:
# Read NFL defensive, yearly, team stats into a pandas Dataframe
# Append a column titled "Year" to each Dataframe



def2022 = pd.read_excel('Data/Defense_2022.csv.xlsx')
def2022['Year'] = '2022'
def2022.rename(columns={
    'Rank': 'D Rank', 
    'Games Played': 'D Games Played', 
    'Fumbles Lost': 'D Fumbles Lost'
}, inplace=True)

def2021 = pd.read_excel('Data/Defense_2021.csv.xlsx')
def2021['Year'] = '2021'
def2021.rename(columns={
    'Rank': 'D Rank', 
    'Games Played': 'D Games Played', 
    'Fumbles Lost': 'D Fumbles Lost'
}, inplace=True)

def2020 = pd.read_excel('Data/Defense_2020.csv.xlsx')
def2020['Year'] = '2020'
def2020.rename(columns={
    'Rank': 'D Rank', 
    'Games Played': 'D Games Played', 
    'Fumbles Lost': 'D Fumbles Lost'
}, inplace=True)

def2019 = pd.read_excel('Data/Defense_2019.csv.xlsx')
def2019['Year'] = '2019'
def2019.rename(columns={
    'Rank': 'D Rank', 
    'Games Played': 'D Games Played', 
    'Fumbles Lost': 'D Fumbles Lost'
}, inplace=True)

def2018 = pd.read_excel('Data/Defense_2018.csv.xlsx')
def2018['Year'] = '2018'
def2018.rename(columns={
    'Rank': 'D Rank', 
    'Games Played': 'D Games Played', 
    'Fumbles Lost': 'D Fumbles Lost'
}, inplace=True)

def2017 = pd.read_excel('Data/Defense_2017.csv.xlsx')
def2017['Year'] = '2017'
def2017.rename(columns={
    'Rank': 'D Rank', 
    'Games Played': 'D Games Played', 
    'Fumbles Lost': 'D Fumbles Lost'
}, inplace=True)

def2016 = pd.read_excel('Data/Defense_2016.csv.xlsx')
def2016['Year'] = '2016'
def2016.rename(columns={
    'Rank': 'D Rank', 
    'Games Played': 'D Games Played', 
    'Fumbles Lost': 'D Fumbles Lost'
}, inplace=True)

def2015 = pd.read_excel('Data/Defense_2015.csv.xlsx')
def2015['Year'] = '2015'
def2015.rename(columns={
    'Rank': 'D Rank', 
    'Games Played': 'D Games Played', 
    'Fumbles Lost': 'D Fumbles Lost'
}, inplace=True)

def2014 = pd.read_excel('Data/Defense_2014.csv.xlsx')
def2014['Year'] = '2014'
def2014.rename(columns={
    'Rank': 'D Rank', 
    'Games Played': 'D Games Played', 
    'Fumbles Lost': 'D Fumbles Lost'
}, inplace=True)

In [7]:
# Remove row 32 to 34 
def2022 = def2022.drop([32,33,34])
def2021 = def2021.drop([32,33,34])
def2020 = def2020.drop([32,33,34])
def2019 = def2019.drop([32,33,34])
def2018 = def2018.drop([32,33,34])
def2017 = def2017.drop([32,33,34])
def2016 = def2016.drop([32,33,34])
def2015 = def2015.drop([32,33,34])
def2014 = def2014.drop([32,33,34])

In [8]:
# Merge response data together
def_merge = [def2022, def2021, def2020, def2019, def2018, def2017, def2016, def2015, def2014]
def_total = pd.concat(def_merge)
def_total['Year'] = def_total['Year'].astype('int')

In [9]:
# Create Training Set
training_set = off_total.merge(def_total, on = ['Team', 'Year'])

In [10]:
#Create Test set to backtest 2023 season accuracy
off2023 = pd.read_excel('Data/Offense_2023.csv.xlsx')
off2023['Year'] = '2023'
off2023.rename(columns={
    'Rank': 'O Rank'
}, inplace=True)
off2023 = off2023.drop([32,33,34])

def2023 = pd.read_excel('Data/Defense_2023.csv.xlsx')
def2023['Year'] = '2023'
def2023.rename(columns={
    'Rank': 'D Rank', 
    'Games Played': 'D Games Played', 
    'Fumbles Lost': 'D Fumbles Lost'
}, inplace=True)
def2023 = def2023.drop([32,33,34])

test_set = off2023.merge(def2023, on = ['Team', 'Year'])

In [11]:
test_set['Year'] = test_set['Year'].astype('int')

In [13]:
all_data = pd.concat([training_set, test_set])
all_data['Year'] = all_data['Year'].astype('int')
all_data['Super Bowl'] = 0

In [14]:
sb_champs = pd.read_excel('Data/Super_Bowl.csv.xlsx')

In [15]:
sb_champs.drop(sb_champs[sb_champs['SB'] == 'LVIII (58)'].index, inplace=True)

In [16]:
sb_champs['Date'] = pd.to_datetime(sb_champs['Date'])
sb_champs['Year'] = pd.DatetimeIndex(sb_champs['Date']).year
sb_champs = sb_champs[['Year', 'Winner']]

In [17]:
sb_champs.loc[:, 'Year'] = sb_champs['Year'] - 1
sb_champs.loc[:, 'Year'] = sb_champs['Year'].astype('object')
sb_champs.loc[:, 'Super_Bowl'] = 1

In [18]:
sb_champs.loc[:, 'Year'] = sb_champs['Year'].astype('int')
all_data.loc[:, 'Year'] = all_data['Year'].astype('int')

In [19]:
final_df = pd.merge(all_data, sb_champs, left_on = ['Year', 'Team'], right_on = ['Year', 'Winner'], how = 'left')

In [21]:
final_df.drop(['Super Bowl', 'Winner'], axis=1, inplace=True)
final_df.loc[:, 'Super_Bowl'] = final_df['Super_Bowl'].fillna(0)
final_df.loc[:, 'Super_Bowl'] = final_df['Super_Bowl'].astype('int')

In [ ]:
final_df

# Modeling

In [47]:
# Split into values for test and train
final_df.loc[:, 'O Rank'] = final_df['O Rank'].astype('int')
final_df.loc[:, 'D Rank'] = final_df['D Rank'].astype('int')

X = np.asarray(final_df.drop(['Team', 'Super_Bowl'], axis=1))
y = np.asarray(final_df['Super_Bowl'])





#X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, test_size=0.25)

In [48]:
# Scale the data

from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)

In [49]:
X_test = X[0:32]
X_train = X[32:]

y_test = y[0:32]
y_train = y[32:]

In [50]:
teams = final_df.loc[ :31 , 'Team']

o_rank = final_df.loc[0:31, 'O Rank']
d_rank = final_df.loc[0:31, 'D Rank']

In [51]:
lr_model = LogisticRegression(C=.01, solver='liblinear').fit(X_train, y_train)

In [52]:
yhat = lr_model.predict(X_test)
yhat

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [53]:
lr_df = pd.DataFrame({'Team':teams, 'Prediction':yhat})
lr_df

                     Team  Prediction
0      Kansas City Chiefs         0.0
1     Philadelphia Eagles         0.0
2          Dallas Cowboys         0.0
3           Buffalo Bills         0.0
4           Detroit Lions         0.0
5     San Francisco 49ers         0.0
6       Minnesota Vikings         0.0
7      Cincinnati Bengals         0.0
8        Seattle Seahawks         0.0
9    Jacksonville Jaguars         0.0
10         Miami Dolphins         0.0
11      Las Vegas Raiders         0.0
12   Los Angeles Chargers         0.0
13      Green Bay Packers         0.0
14        Atlanta Falcons         0.0
15        New York Giants         0.0
16   New England Patriots         0.0
17       Cleveland Browns         0.0
18       Baltimore Ravens         0.0
19      Carolina Panthers         0.0
20      Arizona Cardinals         0.0
21     New Orleans Saints         0.0
22          Chicago Bears         0.0
23  Washington Commanders         0.0
24   Tampa Bay Buccaneers         0.0
25    Pittsburgh Steelers         0.0
26       Los Angeles Rams         0.0
27       Tennessee Titans         0.0
28          New York Jets         0.0
29         Houston Texans         0.0
30     Indianapolis Colts         0.0
31         Denver Broncos         0.0

In [54]:
#Probability
yhat_prob = lr_model.predict_proba(X_test)
yhat_prob

array([[0.55890221, 0.44109779],
       [0.58599747, 0.41400253],
       [0.60561868, 0.39438132],
       [0.61991433, 0.38008567],
       [0.6405648 , 0.3594352 ],
       [0.59227762, 0.40772238],
       [0.62863354, 0.37136646],
       [0.6313725 , 0.3686275 ],
       [0.62788593, 0.37211407],
       [0.59806447, 0.40193553],
       [0.62328906, 0.37671094],
       [0.64521468, 0.35478532],
       [0.60521893, 0.39478107],
       [0.65538518, 0.34461482],
       [0.65640566, 0.34359434],
       [0.65755646, 0.34244354],
       [0.62173892, 0.37826108],
       [0.65044639, 0.34955361],
       [0.61445875, 0.38554125],
       [0.67087633, 0.32912367],
       [0.67772269, 0.32227731],
       [0.63426538, 0.36573462],
       [0.70473676, 0.29526324],
       [0.62402492, 0.37597508],
       [0.61139238, 0.38860762],
       [0.64380739, 0.35619261],
       [0.65760418, 0.34239582],
       [0.69590933, 0.30409067],
       [0.60689527, 0.39310473],
       [0.65596953, 0.34403047],
       [0.66854729, 0.33145271],
       [0.65835523, 0.34164477]])

In [55]:
# O and D rank

lr_df2 = pd.DataFrame({'Team':teams, 'Prediction':yhat_prob[:,1], 'O_Rank':o_rank, 'D_rank':d_rank }) 
lr_df2

                     Team  Prediction  O_Rank  D_rank
0      Kansas City Chiefs    0.441098     1.0    16.0
1     Philadelphia Eagles    0.414003     2.0     8.0
2          Dallas Cowboys    0.394381     3.0     6.0
3           Buffalo Bills    0.380086     4.0     2.0
4           Detroit Lions    0.359435     5.0    29.0
5     San Francisco 49ers    0.407722     6.0     1.0
6       Minnesota Vikings    0.371366     7.0    28.0
7      Cincinnati Bengals    0.368628     8.0     5.0
8        Seattle Seahawks    0.372114     9.0    25.0
9    Jacksonville Jaguars    0.401936    10.0    12.0
10         Miami Dolphins    0.376711    11.0    24.0
11      Las Vegas Raiders    0.354785    12.0    26.0
12   Los Angeles Chargers    0.394781    13.0    21.0
13      Green Bay Packers    0.344615    14.0    17.0
14        Atlanta Falcons    0.343594    15.0    23.0
15        New York Giants    0.342444    16.0    18.0
16   New England Patriots    0.378261    17.0    11.0
17       Cleveland Browns    0.349554    18.0    20.0
18       Baltimore Ravens    0.385541    19.0     3.0
19      Carolina Panthers    0.329124    20.0    19.0
20      Arizona Cardinals    0.322277    21.0    31.0
21     New Orleans Saints    0.365735    22.0     9.0
22          Chicago Bears    0.295263    23.0    32.0
23  Washington Commanders    0.375975    24.0     7.0
24   Tampa Bay Buccaneers    0.388608    25.0    13.0
25    Pittsburgh Steelers    0.356193    26.0    10.0
26       Los Angeles Rams    0.342396    27.0    22.0
27       Tennessee Titans    0.304091    28.0    15.0
28          New York Jets    0.393105    29.0     4.0
29         Houston Texans    0.344030    30.0    27.0
30     Indianapolis Colts    0.331453    31.0    30.0
31         Denver Broncos    0.341645    32.0    14.0

In [57]:
lr_df2 = lr_df2.sort_values(by = ['Prediction'], ascending = False)
lr_df2['Prediction_Rank'] = lr_df2['Prediction'].rank(ascending = False)

lr_df2

                     Team  Prediction  O_Rank  D_rank  Prediction_Rank
0      Kansas City Chiefs    0.441098     1.0    16.0              1.0
1     Philadelphia Eagles    0.414003     2.0     8.0              2.0
5     San Francisco 49ers    0.407722     6.0     1.0              3.0
9    Jacksonville Jaguars    0.401936    10.0    12.0              4.0
12   Los Angeles Chargers    0.394781    13.0    21.0              5.0
2          Dallas Cowboys    0.394381     3.0     6.0              6.0
28          New York Jets    0.393105    29.0     4.0              7.0
24   Tampa Bay Buccaneers    0.388608    25.0    13.0              8.0
18       Baltimore Ravens    0.385541    19.0     3.0              9.0
3           Buffalo Bills    0.380086     4.0     2.0             10.0
16   New England Patriots    0.378261    17.0    11.0             11.0
10         Miami Dolphins    0.376711    11.0    24.0             12.0
23  Washington Commanders    0.375975    24.0     7.0             13.0
8        Seattle Seahawks    0.372114     9.0    25.0             14.0
6       Minnesota Vikings    0.371366     7.0    28.0             15.0
7      Cincinnati Bengals    0.368628     8.0     5.0             16.0
21     New Orleans Saints    0.365735    22.0     9.0             17.0
4           Detroit Lions    0.359435     5.0    29.0             18.0
25    Pittsburgh Steelers    0.356193    26.0    10.0             19.0
11      Las Vegas Raiders    0.354785    12.0    26.0             20.0
17       Cleveland Browns    0.349554    18.0    20.0             21.0
13      Green Bay Packers    0.344615    14.0    17.0             22.0
29         Houston Texans    0.344030    30.0    27.0             23.0
14        Atlanta Falcons    0.343594    15.0    23.0             24.0
15        New York Giants    0.342444    16.0    18.0             25.0
26       Los Angeles Rams    0.342396    27.0    22.0             26.0
31         Denver Broncos    0.341645    32.0    14.0             27.0
30     Indianapolis Colts    0.331453    31.0    30.0             28.0
19      Carolina Panthers    0.329124    20.0    19.0             29.0
20      Arizona Cardinals    0.322277    21.0    31.0             30.0
27       Tennessee Titans    0.304091    28.0    15.0             31.0
22          Chicago Bears    0.295263    23.0    32.0             32.0

# Random Forest Model

In [22]:
# Random forest
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error
import pickle
from sklearn.preprocessing import StandardScaler

In [24]:
# Split into values for test and train
final_df.loc[:, 'O Rank'] = final_df['O Rank'].astype('int')
final_df.loc[:, 'D Rank'] = final_df['D Rank'].astype('int')

X = final_df.drop(['Team', 'Super_Bowl'], axis=1)
y = final_df['Super_Bowl']

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, test_size=0.25)

In [25]:
# Scale the data
scaler = StandardScaler()
X_scaler = scaler.fit(X_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [27]:
rfr_model = RandomForestRegressor(n_estimators= 2000, random_state= 1)

rfr_model.fit(X_train_scaled, y_train)

rfr_predictions = rfr_model.predict(X_test_scaled)

In [29]:
print(mean_absolute_error(y_test, rfr_predictions))

0.07111875

In [ ]:
# Create playoff test dataset from season averages

def Score_Predictor(home_team, away_team):
    team1 = home_team
    team2 = away_team
    
    team1_data = final_df[['Team'] == team1]sb_champs['SB'] == 'LVIII (58)'].index, inplace=True)
    team2_data = rf_model_data[com_data['Team'] == team2].drop('TmScore', axis=1).reset_index(drop=True)